# Generated by Django 6.0.7 on 2026-07-26 09:43

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenerURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Original Link')),
                ('short_code', models.CharField(default=shortener.models.generate_short_code, max_length=10, unique=True, verbose_name='Short code')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Count of transitions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'Shorted link',
                'verbose_name_plural': 'Shrotener link',
                'ordering': ['-created_at'],
            },
        ),
    ]
