# Generated by Django 6.0.7 on 2026-07-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip adress')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of transition')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenerurl', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Log of transition',
                'verbose_name_plural': 'Logs of transitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
