# Generated by Django 6.0.7 on 2026-07-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_clicklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clicklog',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
