# Generated by Django 6.0.7 on 2026-07-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_ip_adress_clicklog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenerurl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
