# Generated by Django 6.0.7 on 2026-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_shortenerurl_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OS'),
        ),
    ]
